backend_user_roles = {
    "Users": {
        "roles": {'View users': 'allow-to-get-users', 'Create users': 'allow-to-create-users',
                  'Delete users': 'allow-to-delete-users', 'Update users': 'allow-to-update-users',
                  'Get user details': 'allow-to-get-user-details', 'Get tenant users': 'allow-to-get-tenant-users',
                  'View user profile': 'allow-to-view-user-profile',
                  'Change user password': 'allow-to-change-user-password',
                  'Get profile picture': 'allow-to-get-profile-picture',
                  'Set profile picture': 'allow-to-set-profile-picture'}},
    "Strangers": {"roles": {'Get stranger activities': 'allow-to-get-stranger-activities',
                            'Get strangers': 'allow-to-get-strangers',
                            'Get unrecognized vehicle activities': 'allow-to-get-unrecognized-vehicle-activities',
                            'Change stranger status': 'allow-to-change-stranger-status'}},
    "Settings": {
        "roles": {'Update threshold': 'allow-to-update-threshold', 'Get threshold': 'allow-to-get-threshold',
                  'Get layout coordinates': 'allow-to-get-layout-coordinates',
                  'Get layout': 'allow-to-get-layout', 'Add layout': 'allow-to-add-layout',
                  'Delete layout': 'allow-to-delete-layout',
                  'Update layout coordinates': 'allow-to-update-layout-coordinates',
                  'Delete layout coordinates': 'allow-to-delete-layout-coordinates',
                  'Get mobile health': 'allow-to-get-mobile-health',
                  'Set mobile health status': 'allow-to-set-mobile-health-status',
                  'Alter db values': 'allow-to_alter_db_values',
                  'Set shift start time': 'allow-to-set-shift-start-time',
                  'Get shift start time': 'allow-to-get-shift-start-time',
                  'Get trial details': 'allow-to-get-trial-details'}},
    "Members": {"roles": {'Get attendance summary': 'allow-to-get-attendance-summary',
                          'Get attendance': 'allow-to-get-attendance',
                          'Get user activities': 'allow-to-get-user-activities',
                          'Get age categories': 'allow-to-get-age-categories',
                          'Create age categories': 'allow-to-create-age-categories',
                          'Delete age categories': 'allow-to-delete-age-categories',
                          'Get user projects': 'allow-to-get-user-projects',
                          'Create user projects': 'allow-to-create-user-projects',
                          'Delete user projects': 'allow-to-delete-user-projects',
                          'Update user projects': 'allow-to-update-user-projects',
                          'Get job categories': 'allow-to-get-job-categories',
                          'Create job categories': 'allow-to-create-job-categories',
                          'Delete job categories': 'allow-to-delete-job-categories',
                          'Update job categories': 'allow-to-update-job-categories',
                          'Get user titles': 'allow-to-get-user-titles',
                          'Create user titles': 'allow-to-create-user-titles',
                          'Delete user titles': 'allow-to-delete-user-titles',
                          'Update user titles': 'allow-to-update-user-titles',
                          'Sanitize sign in status': 'allow_to_sanitize_sign_in_status',
                          'Add records to ES': 'allow-to-add-records-to-es',
                          'Remove records from ES': 'allow-to-remove-records-from-es'}},
    "Locations": {"roles": {'Get locations': 'allow-to-get-locations', 'Create locations': 'allow-to-create-locations',
                            'Update locations': 'allow-to-update-locations',
                            'Delete locations': 'allow-to-delete-locations'}},
    "Insights": {"roles": {'Get usage': 'allow-to-get-usage', 'Get heatmap': 'allow-to-get-heatmap',
                           'Get stats': 'allow-to-get-stats'}},
    "Cameras": {"roles": {'Create cameras': 'allow-to-create-cameras', 'Stop streams': 'allow-to-stop-streams',
                          'Delete cameras': 'allow-to-delete-cameras',
                          'Update cameras': 'allow-to-update-cameras', 'Get cameras': 'allow-to-get-cameras',
                          'Get camera activities': 'allow-to-get-camera-activities',
                          'Start streams': 'allow-to-start-streams',
                          'Get camera details': 'allow-to-get-camera-details'}},
    "Notifications": {"roles": {'Create notification slots': 'allow-to-create-notification-slots',
                                'Update notification slots': 'allow-to-update-notification-slots',
                                'Get notification slots': 'allow-to-get-notification-slots',
                                'Update notification': 'allow-to-get-update-notification',
                                'Get notifications': 'allow-to-get-notification'}},
    "Vehicles": {"roles": {'Get vehicles': 'allow-to-get-vehicles', 'Delete vehicle': 'allow-to-delete-vehicles',
                           'Create vehicle': 'allow-to-create-vehicles',
                           'Update vehicle': 'allow-to-update-vehicle',
                           'Get vehicle attendance summary': 'allow-to-get-vehicle-attendance-summary',
                           'Get vehicle attendance': 'allow-to-get-vehicle-attendance',
                           'Get vehicle activities': 'allow-to-get-vehicle-activities',
                           'Get vehicle details': 'allow-to-get-vehicle-details'}},
    "Login History": {
        "roles": {'Log user login': 'allow-to-log-user-login', 'Log user logout': 'allow-to-log-user-logout',
                  'Get user login history': 'allow-to-get-user-login-history',
                  'Get camera live status': 'allow-to-get-camera-live-status'}},
    "PipelineAdmin": {"roles": {'Add pipeline admin': 'allow-to-add-pipeline-admin',
                                'Get pipeline admin': 'allow-to-get-pipeline-admin',
                                'Delete pipeline admin': 'allow-to-delete-pipeline-admin'}},
    "PipelineConfig": {"roles": {'Get pipeline config': 'allow-to-get-pipeline-config',
                                 'Set pipeline config': 'allow-to-set-pipeline-config'}},
    "User Groups": {
        "roles": {'Get user group': 'allow-to-get-user-group', 'Delete user group': 'allow-to-delete-user-group',
                  'Create user group': 'allow-to-create-user-group',
                  'Update user group': 'allow-to-update-user-group',
                  'Get user group details': 'allow-to-get-user-group-details'}},
    "Work Day Durations": {"roles": {'Get work day durations': 'allow-to-get-work-day-durations',
                                     'Create work day duratios': 'allow-to-create-work-day-durations',
                                     'Delete work day durations': 'allow-to-delete-work-day-durations',
                                     'Update work day durations': 'allow-to-update-work-day-durations'}},
    "Report": {"roles": {'Download attendance report': 'allow-to-download-attendance-report',
                         'Download WDD report': 'allow-to-download-wdd-report'}},
    "Geo Fences": {
        "roles": {'Create geo fence': 'allow-to-create-geo-fences', 'Get geo fence': 'allow-to-get-geo-fences',
                  'Delete geo fence': 'allow-to-delete-geo-fences',
                  'update geo fence': 'allow-to-update-geo-fences'}},
    "Mobile": {
        "roles": {'Log health': 'allow-to-log-health', 'Log error': 'allow-to-log-error',
                  'Get error': 'allow-to-get-error', 'Register device': 'allow-to-register-device',
                  'Recognize person': 'allow-to-recognize-person'}},
    "User Groups Scopes": {"roles": {'Get user group scopes': 'allow-to-get-user-group-scopes',
                                     'Delete user group scopes': 'allow-to-delete-user-group-scopes',
                                     'Create user group scopes': 'allow-to-create-user-group-scopes',
                                     'Update user group scopes': 'allow-to-update-user-group-scopes',
                                     'Get user group scope details': 'allow-to-get-user-group-scopes-details'}},
    "Face Count": {"roles": {'Get face count': 'allow-to-get-face-count'}},
    "ID Card": {"roles": {'Detect ID card': 'allow-to-detect-id-card'}}}
frontend_user_roles = {
    "Settings": {"roles": {"View settings tab": "allow-to-view-settings-tab",
                           "View settings general tab": "allow-to-view-settings-general-tab",
                           "View settings users tab": "allow-to-view-settings-users-tab",
                           "View settings camera tab": "allow-to-view-settings-camera-tab",
                           "View settings floor map tab": "allow-to-view-settings-floor-map-tab",
                           "View settings vehicles tab": "allow-to-view-settings-vehicles-tab",
                           "View settings authorization tab": "allow-to-view-settings-authorization-tab",
                           "View settings login history tab": "allow-to-view-settings-login-history-tab",
                           "View settings location tab": "allow-to-view-settings-location-tab",
                           "View settings work hours distribution tab":
                               "allow-to-view-settings-work-hours-distribution-tab",
                           "View settings general organization": "allow-to-view-settings-general-organization",
                           "View settings general regular stranger frequency":
                               "allow-to-view-settings-general-regular-stranger-frequency",
                           "Edit settings general regular stranger frequency": "allow-to-edit-settings-general-regular-stranger-frequency",
                           "View settings general regular unregistered vehicle frequency": "allow-to-view-settings-general-regular-unregistered-vehicle-frequency",
                           "Edit settings general regular unregistered vehicle frequency": "allow-to-edit-settings-general-regular-unregistered-vehicle-frequency",
                           "View settings general age group": "allow-to-view-settings-general-age-group",
                           "Edit settings general age group": "allow-to-edit-settings-general-age-group",
                           "Add settings user": "allow-to-add-settings-user",
                           "Edit settings user": "allow-to-edit-settings-user",
                           "Delete settings user": "allow-to-delete-settings-user",
                           "Add settings work hours distribution": "allow-to-add-settings-work-hours-distribution",
                           "Edit settings work hours distribution": "allow-to-edit-settings-work-hours-distribution",
                           "Delete settings work hours distribution": "allow-to-delete-settings-work-hours-distribution",
                           "Add settings camera": "allow-to-add-settings-camera",
                           "Edit settings camera": "allow-to-edit-settings-camera",
                           "Delete settings camera": "allow-to-delete-settings-camera",
                           "Edit settings camera timeslots": "allow-to-edit-settings-camera-timeslots",
                           "Upload settings floor map": "allow-to-upload-settings-floor-map",
                           "Save settings floor map coordinates": "allow-to-save-settings-floor-map-coordinates",
                           "Add settings vehicles": "allow-to-add-settings-vehicles",
                           "Edit settings vehicles": "allow-to-edit-settings-vehicles",
                           "Delete settings vehicles": "allow-to-delete-settings-vehicles",
                           "Add settings authorization": "allow-to-add-settings-authorization",
                           "Edit settings authorization": "allow-to-edit-settings-authorization",
                           "Delete settings authorization": "allow-to-delete-settings-authorization",
                           "Add settings location": "allow-to-add-settings-location",
                           "Edit settings location": "allow-to-edit-settings-location",
                           "Delete settings location": "allow-to-delete-settings-location",
                           "View face vehicle toggle": "allow-to-view-face-vehicle-toggle",
                           "Save general fence changes": "allow-to-save-general-fence-changes",
                           "Add user scope": "allow-to-add-user-scope"}},
    "Account": {"roles": {
        "View account tab": "allow-to-view-account-tab",
        "View account general tab": "allow-to-view-account-general-tab",
        "View account users tab": "allow-to-view-account-users-tab",
        "Add account user": "allow-to-add-account-user",
        "Delete account user": "allow-to-delete-account-user",
        "Edit account user": "allow-to-edit-account-user",
        "Change user status": "allow-to-change-user-status"
    }},
    "Attendance": {"roles": {
        "View attendance tab": "allow-to-view-attendance-tab",
        "View attendance summary": "allow-to-view-attendance-summary",
        "View attendance table": "allow-to-view-attendance-table",
        "View attendance work hours summary": "allow-to-view-attendance-work-hours-summary"
    }},
    "Vehicle Attendance": {"roles": {
        "View vehicle attendance tab": "allow-to-view-vehicle-attendance-tab",
        "View vehicle attendance summary": "allow-to-view-vehicle-attendance-summary",
        "View vehicle attendance table": "allow-to-view-vehicle-attendance-table"
    }},
    "Activity": {"roles": {
        "View activity tab": "allow-to-view-activity-tab",
        "View activity users tab": "allow-to-view-activity-users-tab",
        "View activity regular strangers tab": "allow-to-view-activity-regular-strangers-tab",
        "View activity strangers tab": "allow-to-view-activity-strangers-tab",
        "Regular stranger as a user": "allow-to-add-regular-stranger-as-a-user",
        "Change sign in status of a user": "allow-to-change-sign-in-status-of-a-user",
        "Add manual record": "allow-to-add-manual-record",
        "Delete activity record": "allow-to-delete-activity-record"
    }},
    "Vehicle Activity": {"roles": {
        "View vehicle activity tab": "allow-to-view-vehicle-activity-tab",
        "View vehicle activity registered vehicle tab": "allow-to-view-vehicle-activity-registered-vehicle-tab",
        "View vehicle activity regular unregistered vehicle tab": "allow-to-view-vehicle-activity-regular-unregistered-vehicle-tab",
        "View vehicle activity unregistered vehicle tab": "allow-to-view-vehicle-activity-unregistered-vehicle-tab",
        "Add regular unregistered vehicle as a registered vehicle": "allow-to-add-regular-unregistered-vehicle-as-a-registered-vehicle"
    }},
    "Insights": {"roles": {
        "View insights tab": "allow-to-view-insights-tab",
        "View insights usage tab": "allow-to-view-insights-usage-tab",
        "View insights floor heat map tab": "allow-to-view-insights-floor-heat-map-tab",
        "View insights users tab": "allow-to-view-insights-users-tab",
        "View insights usage chart": "allow-to-view-insights-usage-chart",
        "View insights usage table": "allow-to-view-insights-usage-table",
        "View insights users age chart": "allow-to-view-insights-users-age-chart",
        "View insights users gender chart": "allow-to-view-insights-users-gender-chart",
        "View insights users job category chart": "allow-to-view-insights-users-job-category-chart",
        "View insights users project chart": "allow-to-view-insights-users-project-chart",
        'View insight live count stats tab': 'allow-to-view-insight-live-count-stats-tab',
        'View insight object category chart': 'allow-to-view-insight-object-category-chart',
        'View insight weekly count chart': 'allow-to-view-insight-weekly-count-chart'
    }},
    "Vehicle Insights": {"roles": {
        "View vehicle insights tab": "allow-to-view-vehicle-insights-tab",
        "View vehicle insights usage tab": "allow-to-view-vehicle-insights-usage-tab",
        "View vehicle insights floor heat map tab": "allow-to-view-vehicle-insights-floor-heat-map-tab",
        "View vehicle insights vehicles tab": "allow-to-view-vehicle-insights-vehicles-tab",
        "View vehicle insights usage chart": "allow-to-view-vehicle-insights-usage-chart",
        "View vehicle insights usage table": "allow-to-view-vehicle-insights-usage-table",
        "View vehicle insights vehicles registration chart": "allow-to-view-vehicle-insights-vehicles-registration-chart",
        "View vehicle insights vehicles province chart": "allow-to-view-vehicle-insights-vehicles-province-chart",
        "View vehicle insights vehicles company chart": "allow-to-view-vehicle-insights-vehicles-company-chart"
    }},
    "Notifications": {"roles": {
        "View all notification page": "allow-to-view-all-notification-page",
        "View notification alerts": "allow-to-view-notification-alerts",
        "View notification details": "allow-to-view-notification-details",
    }},
    "LiveStream": {"roles": {
        "View live stream tab": "allow-to-view-live-stream-tab",
        "View live stream recently identified": "allow-to-view-live-stream-recently-identified"
    }},
    "Job Category": {"roles": {'View job category tab': 'allow-to-view-job-category-tab',
                               'Add job categories': 'allow-to-add-job-categories',
                               'Edit job categories': 'allow-to-edit-job-categories',
                               'Delete job categories frontend': 'allow-to-delete-job-categories-frontend'
                               }},

    "Title": {"roles": {'View title tab': 'allow-to-view-title-tab',
                        'Add titles': 'allow-to-add-titles',
                        'Edit titles': 'allow-to-edit-titles',
                        'Delete titles': 'allow-to-delete-titles'
                        }},

    "Project": {"roles": {'View project tab': 'allow-to-view-project-tab',
                          'Add project': 'allow-to-add-project',
                          'Edit projects': 'allow-to-edit-projects',
                          'Delete projects': 'allow-to-delete-projects'
                          }},
    "UserProfile": {"roles": {'View user profile frontend': 'allow-to-view-user-profile-frontend',
                              'Edit user profile': 'allow-to-edit-user-profile',
                              'Change user password frontend': 'allow-to-change-user-password-frontend',
                              'Reset user password frontend': 'allow-to-reset-user-password-frontend',
                              "Change user image": "allow-to-change-user-image"
                              }},
    "GeoFencing": {"roles": {'View settings general fence tab': 'allow-to-view-settings-general-fence-tab'
                             }},
    "CountStats": {"roles": {"View vehicle stats": "allow-to-view-vehicle-stats",
                             "View face stats": "allow-to-view-face-stats",
                             'View live count tab': 'allow-to-view-live-count-tab',
                             'View face stat chart': 'allow-to-view-face-stat-chart',
                             'View face stat table': 'allow-to-view-face-stat-table',
                             'View vehicle stat chart': 'allow-to-view-vehicle-stat-chart',
                             'View vehicle stat table': 'allow-to-view-vehicle-stat-table',
                             'View live count detailed view': 'allow-to-view-live-count-detailed-view',
                             'View live count dashboard': 'allow-to-view-live-count-dashboard'}},
    "Reports": {"roles": {
        "View geo location tab": "allow-to-view-geo-location-tab",
        "Download attendance report": "allow-to-download-attendance-report",
        "Download attendance summary report": "allow-to-download-attendance-summary-report",
        "Download user activity report": "allow-to-download-user-activity-report",
        "Download regular stranger activity report": "allow-to-download-regular-stranger-activity-report",
        "Download stranger activity report": "allow-to-download-stranger-activity-report",
        "Download usage report": "allow-to-download-usage-report",
        "Download user chart report": "allow-to-download-user-chart-report",
        "Download account users report": "allow-to-download-account-users-report",
        "Download object count report": "allow-to-download-object-count-report",
        "Download camera report": "allow-to-download-camera-report",
        "Download location report": "allow-to-download-location-report",
        "Download login history report": "allow-to-download-login-history-report",
        'Download live count report': 'allow-to-download-live-count-report'
    }},
    "About us": {"roles": {
        "View about us": "allow-to-view-about-us",
        "Download privacy policy": "allow-to-download-privacy-policy",
        "Download terms and conditions": "allow-to-download-terms-and-conditions"
    }}

}
